services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: charles
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pet-book
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U charles -d pet-book"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
