export const breedBySpecies: Record<
  string,
  { label: string; value: string }[]
> = {
  cachorro: [
    { label: 'Husky Siberiano', value: 'husky siberiano' },
    { label: 'Labrador Retriever', value: 'labrador retriever' },
    { label: 'Poodle', value: 'poodle' },
    { label: 'Bulldog', value: 'bulldog' },
    { label: 'Golden Retriever', value: 'golden retriever' },
    { label: 'Shih Tzu', value: 'shih tzu' },
    { label: 'Beagle', value: 'beagle' },
    { label: 'Yorkshire Terrier', value: 'yorkshire terrier' },
    { label: 'Pastor Alemão', value: 'pastor alemao' },
    { label: 'Rottweiler', value: 'rottweiler' },
    { label: 'Doberman', value: 'doberman' },
    { label: 'Boxer', value: 'boxer' },
    { label: 'Pit Bull', value: 'pit bull' },
    { label: 'Chihuahua', value: 'chihuahua' },
    { label: 'Pug', value: 'pug' },
    { label: 'Dachshund (Salsicha)', value: 'dachshund' },
    { label: 'Border Collie', value: 'border collie' },
    { label: 'Australian Shepherd', value: 'australian shepherd' },
    { label: 'Bernese Mountain Dog', value: 'bernese mountain dog' },
    { label: 'Saint Bernard', value: 'saint bernard' },
    { label: 'Great Dane', value: 'great dane' },
    { label: 'Mastiff', value: 'mastiff' },
    { label: 'Cane Corso', value: 'cane corso' },
    { label: 'Dogo Argentino', value: 'dogo argentino' },
    { label: 'Fila Brasileiro', value: 'fila brasileiro' },
    { label: 'Vira-lata', value: 'vira-lata' },
    { label: 'Pinscher', value: 'pinscher' },
    { label: 'Lulu da Pomerânia', value: 'lulu da pomerania' },
    { label: 'Maltês', value: 'maltes' },
    { label: 'Bichon Frisé', value: 'bichon frise' },
    { label: 'Cocker Spaniel', value: 'cocker spaniel' },
    { label: 'Setter Irlandês', value: 'setter irlandes' },
    { label: 'Pointer', value: 'pointer' },
    { label: 'Weimaraner', value: 'weimaraner' },
    { label: 'Vizsla', value: 'vizsla' },
    { label: 'Rhodesian Ridgeback', value: 'rhodesian ridgeback' },
    { label: 'Akita', value: 'akita' },
    { label: 'Shiba Inu', value: 'shiba inu' },
    { label: 'Chow Chow', value: 'chow chow' },
    { label: 'Shar Pei', value: 'shar pei' },
    { label: 'Pequinês', value: 'pequines' },
    { label: 'Lhasa Apso', value: 'lhasa apso' },
    { label: 'Tibetan Terrier', value: 'tibetan terrier' },
    { label: 'Samoyed', value: 'samoyed' },
    { label: 'Malamute do Alasca', value: 'malamute do alasca' },
    { label: 'Chow Chow', value: 'chow chow' },
    { label: 'Basset Hound', value: 'basset hound' },
    { label: 'Bloodhound', value: 'bloodhound' },
    { label: 'Foxhound', value: 'foxhound' },
    { label: 'Jack Russell Terrier', value: 'jack russell terrier' },
    {
      label: 'West Highland White Terrier',
      value: 'west highland white terrier',
    },
    { label: 'Scottish Terrier', value: 'scottish terrier' },
    { label: 'Airedale Terrier', value: 'airedale terrier' },
    { label: 'Bull Terrier', value: 'bull terrier' },
    {
      label: 'Staffordshire Bull Terrier',
      value: 'staffordshire bull terrier',
    },
    {
      label: 'American Staffordshire Terrier',
      value: 'american staffordshire terrier',
    },
    { label: 'Boston Terrier', value: 'boston terrier' },
    { label: 'French Bulldog', value: 'french bulldog' },
    { label: 'English Bulldog', value: 'english bulldog' },
    { label: 'American Bulldog', value: 'american bulldog' },
    {
      label: 'Cavalier King Charles Spaniel',
      value: 'cavalier king charles spaniel',
    },
    { label: 'King Charles Spaniel', value: 'king charles spaniel' },
    { label: 'Papillon', value: 'papillon' },
    { label: 'Pomeranian', value: 'pomeranian' },
    { label: 'Keeshond', value: 'keeshond' },
    { label: 'Schipperke', value: 'schipperke' },
    { label: 'Belgian Malinois', value: 'belgian malinois' },
    { label: 'Belgian Tervuren', value: 'belgian tervuren' },
    { label: 'Belgian Sheepdog', value: 'belgian sheepdog' },
    { label: 'Dutch Shepherd', value: 'dutch shepherd' },
    { label: 'Collie', value: 'collie' },
    { label: 'Shetland Sheepdog', value: 'shetland sheepdog' },
    { label: 'Welsh Corgi Pembroke', value: 'welsh corgi pembroke' },
    { label: 'Welsh Corgi Cardigan', value: 'welsh corgi cardigan' },
    { label: 'Australian Cattle Dog', value: 'australian cattle dog' },
    { label: 'Blue Heeler', value: 'blue heeler' },
    { label: 'Red Heeler', value: 'red heeler' },
    { label: 'Kelpie', value: 'kelpie' },
    { label: 'Newfoundland', value: 'newfoundland' },
    { label: 'Leonberger', value: 'leonberger' },
    { label: 'Landseer', value: 'landseer' },
    { label: 'Terra Nova', value: 'terra nova' },
    { label: 'Hovawart', value: 'hovawart' },
    { label: 'Kuvasz', value: 'kuvasz' },
    { label: 'Komondor', value: 'komondor' },
    { label: 'Puli', value: 'puli' },
    { label: 'Pumi', value: 'pumi' },
    { label: 'Mudi', value: 'mudi' },
    { label: 'Beauceron', value: 'beauceron' },
    { label: 'Briard', value: 'briard' },
    { label: 'Picardy Shepherd', value: 'picardy shepherd' },
    { label: 'Bearded Collie', value: 'bearded collie' },
    { label: 'Old English Sheepdog', value: 'old english sheepdog' },
    { label: 'Polish Lowland Sheepdog', value: 'polish lowland sheepdog' },
    { label: 'Bergamasco', value: 'bergamasco' },
    { label: 'Catalan Sheepdog', value: 'catalan sheepdog' },
    { label: 'Portuguese Water Dog', value: 'portuguese water dog' },
    { label: 'Spanish Water Dog', value: 'spanish water dog' },
    { label: 'Irish Water Spaniel', value: 'irish water spaniel' },
    { label: 'American Water Spaniel', value: 'american water spaniel' },
    { label: 'Boykin Spaniel', value: 'boykin spaniel' },
    {
      label: 'Nova Scotia Duck Tolling Retriever',
      value: 'nova scotia duck tolling retriever',
    },
    { label: 'Flat-Coated Retriever', value: 'flat-coated retriever' },
    { label: 'Curly-Coated Retriever', value: 'curly-coated retriever' },
    { label: 'Chesapeake Bay Retriever', value: 'chesapeake bay retriever' },
    { label: 'Irish Setter', value: 'irish setter' },
    { label: 'English Setter', value: 'english setter' },
    { label: 'Gordon Setter', value: 'gordon setter' },
  ],
  gato: [
    { label: 'Vira-lata', value: 'vira-lata' },
    { label: 'Persa', value: 'persa' },
    { label: 'Siamês', value: 'siames' },
    { label: 'Maine Coon', value: 'maine coon' },
    { label: 'Ragdoll', value: 'ragdoll' },
    { label: 'Bengal', value: 'bengal' },
    { label: 'Sphynx (Sem pelo)', value: 'sphynx' },
    { label: 'British Shorthair', value: 'british shorthair' },
  ],
  peixe: [
    { label: 'Betta', value: 'betta' },
    { label: 'Tetra Neon', value: 'tetra neon' },
    { label: 'Guppy', value: 'guppy' },
    { label: 'Molly', value: 'molly' },
    { label: 'Peixe Dourado', value: 'peixe dourado' },
  ],
  passaro: [
    { label: 'Calopsita', value: 'calopsita' },
    { label: 'Periquito', value: 'periquito' },
    { label: 'Papagaio', value: 'papagaio' },
    { label: 'Canário', value: 'canario' },
  ],
  coelho: [
    { label: 'Cabeça de Leão (Lionhead)', value: 'cabeca de leao' },
    { label: 'Mini Lop', value: 'mini lop' },
    { label: 'Angorá', value: 'angora' },
    { label: 'Rex', value: 'rex' },
  ],
  hamster: [
    { label: 'Sírio', value: 'sirio' },
    { label: 'Anão Russo', value: 'anao russo' },
    { label: 'Campbell', value: 'campbell' },
    { label: 'Roborovski', value: 'roborovski' },
  ],
  'porquinho-da-india': [
    { label: 'Peruano', value: 'peruano' },
    { label: 'Teddy', value: 'teddy' },
    { label: 'Texel', value: 'texel' },
    { label: 'Abissínio', value: 'abissinio' },
  ],
  tartaruga: [
    {
      label: 'Tartaruga de Orelha Vermelha',
      value: 'tartaruga de orelha vermelha',
    },
    { label: 'Tartaruga de Galápagos', value: 'tartaruga de galapagos' },
    { label: 'Tartaruga Leopardo', value: 'tartaruga leopardo' },
  ],
  cobra: [
    { label: 'Píton Real', value: 'piton real' },
    { label: 'Cobra do Milho', value: 'cobra do milho' },
    { label: 'Jiboia', value: 'jiboia' },
  ],
  lagarto: [
    { label: 'Dragão Barbudo', value: 'dragao barbudo' },
    { label: 'Gecko Leachianus', value: 'gecko leachianus' },
    { label: 'Gecko Leopardo', value: 'gecko leopardo' },
  ],
  furao: [{ label: 'Furão Comum', value: 'furao comum' }],
  cavalo: [
    { label: 'Quarto de Milha', value: 'quarto de milha' },
    { label: 'Puro Sangue Inglês', value: 'puro sangue ingles' },
    { label: 'Mangalarga Marchador', value: 'mangalarga marchador' },
  ],
}
